### ISSUE TITLE
Dragging variable pill doesn't work when editing SMS destination of trigger

### ISSUE THREAD

**Issue by juanedi** [instedd/mbuilder#231]
To reproduce:

- Go to the external trigger creation screen
- Add an additional parameter
- Add a new SMS step
- Enter some text into the "to:"  field of the SMS step, and then delete it
- Try to drag the pill of the previously defined parameter to the destination field.

The variable is not bound to the field. This problem doesn't occur when dragging the pill without having previously entered some text.

**Comment by nditada** [comment]
@bcardiff Was this solver by fixing #203?

**Comment by bcardiff** [comment]
No. Still present.

**Comment by bcardiff** [comment]
Will solve togther with #297 since the control to be used is similar.
Will add support for removing pill with an 'x' and going back to an empty state.

Expected UI:
![screen shot 2015-05-14 at 4 50 09 pm](https://cloud.githubusercontent.com/assets/459923/7640378/520e0d6c-fa59-11e4-823d-fc9adfbc457f.png)

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
