### ISSUE TITLE
Check for protocols of entity sets 

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#245]
mBuilder is assuming any entitySet supports updates and inserts without querying the protocol. That results in bugs when attempting to write on a read only entityset. mBuilder already supports read-only tables. When an entityset does not support update/inserts, show it as readonly.

**Comment by pmallol** [comment]
Found in v.1.2-pre2

It is still possible to add pills to a 'read only' table from resource map (added from Resource map or through Hub) and save the message trigger. After a sandbox test an error message shows up reading: 
"Error: unexpected character at line 1, column 1 [parse.c:637]".
Poirot log: http://poirot-stg.instedd.org/activities/5af3286c-560e-fdec-d0ec-4bfeb595e994

**Comment by ggiraldez** [comment]
Support for protocols is up in mBuilder, but:
 - for direct Resmap tables, the protocols are hard-coded to query, update, insert in mBuilder JS code (see `resource_map_controller.coffee:46`)
 - for Resmap tables coming from Hub, the protocols must be queried by Hub and reflected back to mBuilder

**Comment by vtiffenberg** [comment]
- I'm going to have to add en endpoint en Resource Map to allow the user to know their own permissions, otherwise I can't know what protocols are allowed. 
- What should we do with users who have partial update permissions? As in, a user has reading permissions for a layer but not for another: do we let them see the whole form and fail when trying to update a field which is not allowed or do we not allow for updates at all? Same goes for reading permissions.

**Comment by vtiffenberg** [comment]
With tables straight from ResourceMap actually do have a more descriptive error: "Error: Forbidden - Check the API documentation: https://github.com/instedd/resourcemap/wiki/REST_API"

Talking with Martín we thought that the endpoint with very specific Hub data does not make much sense from ResourceMap's side. Another view we thought we could take is making the error handling from Hub more descriptive so as to fail because of lack of permissions but more elegantly.

**Comment by nditada** [comment]
Yes, just a descriptive error explaining that the user doesn't have enough permissions is fine for now. Make sure it shows up nicely and clear in the sandbox and in the activity log.

**Comment by vtiffenberg** [comment]
Pushed into Hub (https://github.com/instedd/hub/commit/0eed371c64e1630090e7b935a9cc90be40e17359) error handling for the API. It now returns the Forbidden message that ResourceMap does.

**Comment by mmuller** [comment]
Ok in version 1.2-pre3
