### ISSUE TITLE
Validation triggers are not working

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#344]
Steps to reproduce:

1. Create a trigger, create a  "colors" table with a "name" column
2. Store the message as a new value for that column.
3. Right click on the column and setup a validation with 'red, yellow, blue'.
4. Click on the validation trigger link
5. Add a validation error message.
6. Click 'save'.

Result: error message
Expected: the trigger gets saved and the user is taken back to the previous trigger.

Note: I tried saving the first trigger before clicking on the validation trigger link, but that still results in an error when saving the new validation trigger.

381 and 349 are examples of final state: triggers list becomes unaccessible.

**Comment by asterite** [comment]
The problem seems to happen only in production because an icon is missing for the "Validation Triggers" section when there are no triggers. In development the error of an icon not found is silently ignored.

@jkicillof Could you design an icon for this? Similar to the ones for "Periodic Task" and "External Triggers", but for "Validation Triggers".

![screenshot 2016-07-26 15 23 12](https://cloud.githubusercontent.com/assets/209371/17150219/f9cc84ee-5344-11e6-9ead-c2892283b875.png)

**Comment by asterite** [comment]
There's a separate issue that you can't create a validation trigger before creating a trigger with a table, and saving that table.

**Comment by asterite** [comment]
Oh, actually, there's no icon for that because the section is missing, but a method is invoked that still requires an asset... I'll just use an existing asset.

**Comment by jkicillof** [comment]
Use this icon from the platform icon set
![image](https://cloud.githubusercontent.com/assets/5031636/17348660/29a2f028-58ee-11e6-96ec-dce60bf4c794.png)

**Comment by nditada** [comment]
@asterite is this solved? can we close it?

**Comment by asterite** [comment]
Yes, closed :-)

I created an issue related to this one: #347
